export const taresProv= [
  {
    id: 1,
    titulo: 'Diseñar endpoint de autenticación',
    descripcion: 'Crear ruta /api/auth con JWT y validaciones',
    tiempoMin: 120,
    labory: 3,
    efectivo: 250,
    fechaEntrega: '2026-07-05T00:00:00.000Z',
    status: 'publicada',
    nivel: 'general',
    recurrencia: 'unica',
  },
  {
    id: 2,
    titulo: 'Corregir bug en dashboard',
    descripcion: 'El gráfico de métricas no refresca al cambiar de tab',
    tiempoMin: 45,
    labory: 1,
    efectivo: 80,
    fechaEntrega: '2026-07-02T00:00:00.000Z',
    status: 'publicada',
    nivel: 'general',
    recurrencia: 'unica',
  },
  {
    id: 3,
    titulo: 'Sin título',
    descripcion: 'Sin descripción',
    tiempoMin: 0,
    labory: 0,
    efectivo: 0,
    fechaEntrega: null,
    status: 'publicada',
    nivel: 'general',
    recurrencia: 'unica',
  },
  {
    id: 4,
    titulo: 'Optimizar consultas PostgreSQL',
    descripcion: 'Agregar índices a tabla de tareas',
    tiempoMin: 90,
    labory: 2,
    efectivo: 150,
    fechaEntrega: '2026-07-10T00:00:00.000Z',
    status: 'publicada',
    nivel: 'general',
    recurrencia: 'unica',
  },
  {
    id: 5,
    titulo: 'Documentar API con Swagger',
    descripcion: 'Cubrir endpoints de tareas y todos',
    tiempoMin: 60,
    labory: 1,
    efectivo: 100,
    fechaEntrega: '2026-07-15T00:00:00.000Z',
    status: 'publicada',
    nivel: 'general',
    recurrencia: 'unica',
  },
]